export enum JiraError {
  ERROR_ON_RETRIEVE_TOKEN = 'ERROR_ON_RETRIEVE_TOKEN',
  ERROR_ON_RETRIEVE_CLOUD_ID = 'ERROR_ON_RETRIEVE_CLOUD_ID',
  ERROR_GETTING_CLOUD_ID = 'ERROR_GETTING_CLOUD_ID',
  ERROR_ON_GET_TOKEN = 'ERROR_ON_GET_TOKEN',
  ERROR_ON_REFRESH_TOKEN = 'ERROR_ON_REFRESH_TOKEN',
  ERROR_GETTING_ACCOUNT_ID = 'ERROR_GETTING_ACCOUNT_ID',
  USER_NOT_EXISTS = 'USER_NOT_EXISTS',
}
