export enum TempoError {
  ERROR_ON_RETRIEVE_TOKEN = 'ERROR_ON_RETRIEVE_TOKEN',
  ERROR_ON_GET_TOKEN = 'ERROR_ON_GET_TOKEN',
  ERROR_ON_REFRESH_TOKEN = 'ERROR_ON_REFRESH_TOKEN',
  ERROR_GETTING_WORKLOG_FOR_USER = 'ERROR_GETTING_WORKLOG_FOR_USER',
  ERROR_ON_RETRIEVE_WORKLOG_FOR_USER = 'ERROR_ON_RETRIEVE_WORKLOG_FOR_USER',
  ERROR_ON_CALCULATE_WORKED_HOURS = 'ERROR_ON_CALCULATE_WORKED_HOURS',
}
